sudo: false
language: node_js
node_js:
  - '11.15.0'
branches:
  only:
    - devellop
install:
  - npm install
  - npm install -g coveralls
cache:
  directories:
    - node_modules
before_script:
  - plsql -c 'create database test;' -U postgres
  - cat .config/travis.application.properties > src/main/resources/application.properties
env: DB=test
script:
  - npm run test

after_success:
  - npm run coveralls
